import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { ShieldCheck, RefreshCw } from "lucide-react";
import { toast } from "sonner";

interface DeliveryPinCardProps {
  orderId: string;
  /** PIN we already know about (saved on this device when the order was placed). */
  localPin?: string;
  onPinChanged?: (pin: string) => void;
}

/**
 * Shows the customer their active delivery PIN and lets them ask for a fresh
 * one if it never arrived. A new PIN replaces the old one immediately, so the
 * driver's normal PIN check keeps working exactly as before.
 */
const DeliveryPinCard = ({ orderId, localPin, onPinChanged }: DeliveryPinCardProps) => {
  const [pin, setPin] = useState(localPin || "");
  const [sending, setSending] = useState(false);

  // A PIN regenerated by the driver or an admin lives on the order, so pull it in.
  useEffect(() => {
    let alive = true;
    const load = async () => {
      const { data } = await supabase.rpc("get_active_delivery_pin" as any, {
        p_order_id: orderId,
      });
      const serverPin = (data as string | null) ?? "";
      if (alive && serverPin) {
        setPin(serverPin);
        onPinChanged?.(serverPin);
      }
    };
    load();
    const timer = setInterval(load, 20000);
    return () => {
      alive = false;
      clearInterval(timer);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [orderId]);

  const resend = async () => {
    setSending(true);
    const { data, error } = await supabase.rpc("regenerate_delivery_pin" as any, {
      p_order_id: orderId,
    });
    if (error) {
      console.error("resend delivery pin failed", error);
      toast.error(error.message || "Could not create a new PIN. Please try again.");
    } else if (data) {
      setPin(data as string);
      onPinChanged?.(data as string);
      toast.success("Here is your new delivery PIN — give it to the driver");
    }
    setSending(false);
  };

  return (
    <div className="mb-3 rounded-lg border border-primary/20 bg-primary/5 px-3 py-2">
      <div className="flex flex-wrap items-center gap-2">
        <ShieldCheck className="h-4 w-4 shrink-0 text-primary" />
        <span className="text-xs text-muted-foreground">Delivery PIN:</span>
        <span className="text-base font-bold tracking-[0.3em] text-primary">
          {pin || "——————"}
        </span>
        <button
          onClick={resend}
          disabled={sending}
          className="ml-auto flex items-center gap-1.5 rounded-lg border border-primary/30 bg-card px-2.5 py-1.5 text-[11px] font-bold text-primary disabled:opacity-50"
        >
          <RefreshCw className={`h-3.5 w-3.5 ${sending ? "animate-spin" : ""}`} />
          {sending ? "Sending…" : "Resend PIN"}
        </button>
      </div>
      <p className="mt-1 text-[10px] text-muted-foreground">
        Share this PIN with your driver on arrival. Didn't get it? Tap Resend PIN.
      </p>
    </div>
  );
};

export default DeliveryPinCard;
