// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/tools/list-restaurants.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.96.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not signed in to Mfula Deliveries." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-restaurants.ts
var list_restaurants_default = defineTool({
  name: "list_restaurants",
  title: "List restaurants",
  description: "List restaurants available for delivery on Mfula Deliveries, optionally filtered by a name or cuisine search term.",
  inputSchema: {
    search: z.string().trim().optional().describe("Optional name or cuisine search term."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("restaurants").select("id, name, cuisine, location, delivery_time, min_order, rating, is_active, is_open").eq("is_active", true).order("rating", { ascending: false }).limit(limit ?? 20);
    if (search) query = query.or(`name.ilike.%${search}%,cuisine.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { restaurants: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-restaurant-menu.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var get_restaurant_menu_default = defineTool2({
  name: "get_restaurant_menu",
  title: "Get restaurant menu",
  description: "Get the available menu items and prices for one restaurant by its id.",
  inputSchema: {
    restaurant_id: z2.string().uuid().describe("Restaurant id from list_restaurants."),
    category: z2.string().trim().optional().describe("Optional menu category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ restaurant_id, category }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("menu_items").select("id, name, description, category, price, is_available, is_popular").eq("restaurant_id", restaurant_id).eq("is_available", true).order("category", { ascending: true });
    if (category) query = query.ilike("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_orders_default = defineTool3({
  name: "list_my_orders",
  title: "List my orders",
  description: "List the signed-in customer's recent Mfula Deliveries orders, newest first.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Maximum results (default 10)."),
    status: z3.string().trim().optional().describe("Optional order status filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("orders").select(
      "id, order_number, restaurant, status, total, delivery_fee, payment_method, payment_status, created_at, delivered_at"
    ).eq("customer_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/track-order.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z4 } from "npm:zod@^3.25.76";
var track_order_default = defineTool4({
  name: "track_order",
  title: "Track an order",
  description: "Get the current delivery status and timeline of one of the signed-in customer's orders by order number.",
  inputSchema: {
    order_number: z4.number().int().positive().describe("The order number shown in the app.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_number }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("orders").select(
      "order_number, restaurant, status, total, delivery_fee, payment_status, items, customer_address, created_at, accepted_at, picked_up_at, arrived_at, delivered_at, cancelled_at, cancel_reason"
    ).eq("customer_id", ctx.getUserId()).eq("order_number", order_number).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return {
        content: [{ type: "text", text: `No order #${order_number} found on your account.` }],
        isError: true
      };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kdplufybixfqsqhyixxw";
var mcp_default = defineMcp({
  name: "mfula-deliveries",
  title: "Mfula Deliveries",
  version: "0.1.0",
  instructions: "Tools for Mfula Deliveries, a food delivery app in Mfuleni, Cape Town. Use `list_restaurants` to find open restaurants, `get_restaurant_menu` for their items and prices, `list_my_orders` for the signed-in customer's order history, and `track_order` for the live status of a specific order number. All tools act as the signed-in customer.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_restaurants_default, get_restaurant_menu_default, list_my_orders_default, track_order_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
